
-- BEGIN: Insert greetings table
INSERT INTO greetings (message)
VALUES ('Hello'),
       ('こんにちは'),
       ('Bonjour'),
       ('Hola'),
       ('Ciao'),
       ('안녕하세요'),
       ('Guten Tag'),
       ('Olá'),
       ('नमस्ते'),
       ('Привет'),
       ('Merhaba'),
       ('مرحبا'),
       ('你好'),
       ('สวัสดี'),
       ('გამარჯობა'),
       ('שלום'),
       ('مرحبًا'),
       ('Hej'),
       ('Hallå'),
       ('Hei'),
       ('Hei hei'),
       ('Hej hej'),
       ('Hoi'),
       ('Hallo'),
       ('Halo'),
       ('Ahoj'),
       ('Прывітанне'),
       ('Привіт'),
       ('Здравейте'),
       ('Здраво'),
       ('Բարեւ'),
       ('Olá');
-- END: Insert greetings table
