apiVersion: v1
kind: Pod
metadata:
  annotations:
    cni.projectcalico.org/containerID: 04ff5c33d70d9bf72c30a28f648e157130de67d407f69664859126b1434a002b
    cni.projectcalico.org/podIP: 10.72.1.12/32
    cni.projectcalico.org/podIPs: 10.72.1.12/32
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Pod","metadata":{"name":"sample-pod","namespace":"default"},"spec":{"containers":[{"image":"nginx:1.16","name":"nginx-container"}]}}
  creationTimestamp: "2021-11-21T00:56:35Z"
  name: sample-pod
  namespace: default
  resourceVersion: "6985"
  uid: 28d2ffd3-e6bc-4b01-b0ce-cd4ee00f070b
spec:
  containers:
  - image: nginx:1.17
    imagePullPolicy: IfNotPresent
    name: nginx-container
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-2pdzr
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: gke-k8s-default-pool-4dc9af00-rlhx
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-2pdzr
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2021-11-21T00:56:35Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2021-11-21T00:56:36Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2021-11-21T00:56:36Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2021-11-21T00:56:35Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://5da90486814bb72e64a1e970daf8c8b7b248e6ce837e0aa49dbc0dfab774db07
    image: docker.io/library/nginx:1.17
    imageID: docker.io/library/nginx@sha256:6fff55753e3b34e36e24e37039ee9eae1fe38a6420d8ae16ef37c92d1eb26699
    lastState:
      terminated:
        containerID: containerd://e97e7babb2e4fe34e8df989bf29a1983c13c86c68fba5f8d7e303c3009121bd7
        exitCode: 0
        finishedAt: "2021-11-21T01:01:15Z"
        reason: Completed
        startedAt: "2021-11-21T00:59:33Z"
    name: nginx-container
    ready: true
    restartCount: 3
    started: true
    state:
      running:
        startedAt: "2021-11-21T01:01:15Z"
  hostIP: 10.146.0.12
  phase: Running
  podIP: 10.72.1.12
  podIPs:
  - ip: 10.72.1.12
  qosClass: BestEffort
  startTime: "2021-11-21T00:56:35Z"
