apiVersion: v1
kind: Pod
metadata:
  annotations:
    cni.projectcalico.org/containerID: 04ff5c33d70d9bf72c30a28f648e157130de67d407f69664859126b1434a002b
    cni.projectcalico.org/podIP: 10.72.1.12/32
    cni.projectcalico.org/podIPs: 10.72.1.12/32
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Pod","metadata":{"name":"sample-pod","namespace":"default"},"spec":{"containers":[{"image":"nginx:1.16","name":"nginx-container"}]}}
  creationTimestamp: "2021-11-21T00:56:35Z"
  name: sample-pod
  namespace: default
  resourceVersion: "6335"
  uid: 28d2ffd3-e6bc-4b01-b0ce-cd4ee00f070b
spec:
  containers:
  - image: nginx:1.16
    imagePullPolicy: IfNotPresent
    name: nginx-container
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-2pdzr
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: gke-k8s-default-pool-4dc9af00-rlhx
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-2pdzr
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2021-11-21T00:56:35Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2021-11-21T00:56:36Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2021-11-21T00:56:36Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2021-11-21T00:56:35Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://e97e7babb2e4fe34e8df989bf29a1983c13c86c68fba5f8d7e303c3009121bd7
    image: docker.io/library/nginx:1.16
    imageID: docker.io/library/nginx@sha256:d20aa6d1cae56fd17cd458f4807e0de462caf2336f0b70b5eeb69fcaaf30dd9c
    lastState:
      terminated:
        containerID: containerd://ba5b784bbd140c50172f7e704ed9c6e7bb8952d7f4eb0382e794f1bdddcba751
        exitCode: 0
        finishedAt: "2021-11-21T00:59:33Z"
        reason: Completed
        startedAt: "2021-11-21T00:58:17Z"
    name: nginx-container
    ready: true
    restartCount: 2
    started: true
    state:
      running:
        startedAt: "2021-11-21T00:59:33Z"
  hostIP: 10.146.0.12
  phase: Running
  podIP: 10.72.1.12
  podIPs:
  - ip: 10.72.1.12
  qosClass: BestEffort
  startTime: "2021-11-21T00:56:35Z"
