[project]
name = "fileeditor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mcp[cli]>=1.2.0",
]

[dependency-groups]
dev = [
    "black>=24.10.0",
]
