# Generated by Django 4.2.5 on 2023-09-10 13:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="choice",
            name="votes2",
            field=models.IntegerField(default=0),
        ),
    ]
